name: Deployment on Dockerhub

on:
  push:
    branches:
      - "main"

jobs:
  build:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/spring-app:latest .

      - name: Push Image to Docker Hub
        run: docker push ${{ secrets.DOCKER_USERNAME }}/spring-app:latest

  deploy:
    needs: build
    runs-on: self-hosted

    steps:
      - name: Pull docker image
        run: sudo docker pull ${{ secrets.DOCKER_USERNAME }}/spring-app:latest

      - name: Delete old container
        run: sudo docker rm -f spring-app-container || true
  
      - name: Run docker container          
        run: sudo docker run -d -p 8080:8080 --init --name spring-app-container ${{ secrets.DOCKER_USERNAME }}/spring-app:latest